CREATE TABLE `public`.`user` (
  `userId` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `emailAddress` VARCHAR(45) NULL,
  `lastUpdateDate` DATETIME NOT NULL,
  `lastUpdatedBy` VARCHAR(50) NULL,
  `createdDate` DATETIME NOT NULL,
  `createdBy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `idUser_UNIQUE` (`userId` ASC) VISIBLE);

ALTER TABLE `public`.`user`
  CHANGE COLUMN `userId` `userId` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE `public`.`finances_key` (
  `TABLE_NAME` INT NOT NULL,
  `VALUE` INT NULL,
  PRIMARY KEY (`TABLE_NAME`),
  UNIQUE INDEX `VALUE_UNIQUE` (`VALUE` ASC) VISIBLE)
  COMMENT = 'Stores the ids of primary keys ';

ALTER TABLE `public`.`finances_keys`
  CHANGE COLUMN `TABLE_NAME` `TABLE_NAME` VARCHAR(15) NOT NULL ,
  CHANGE COLUMN `VALUE` `VALUE` INT(11) NOT NULL ,
  ADD UNIQUE INDEX `TABLE_NAME_UNIQUE` (`TABLE_NAME` ASC) VISIBLE,
  DROP INDEX `VALUE_UNIQUE` ;
;

CREATE TABLE `public`.`time_test` (
  `timeTestId` INT NOT NULL,
  `dateTime` DATETIME NULL,
  `timeStamp` TIMESTAMP NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `sqlDateTime` DATETIME NULL,
  `sqlDate` DATE NULL,
  `sqlTime` TIME NULL,
  PRIMARY KEY (`timeTestId`),
  UNIQUE INDEX `timeTestId_UNIQUE` (`timeTestId` ASC) VISIBLE);

ALTER TABLE `public`.`time_test`
  CHANGE COLUMN `timeTestId` `timeTestId` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `public`.`time_test`
  ADD COLUMN `sqlTimeStamp` TIMESTAMP NULL AFTER `sqlDateTime`;

DROP TABLE IF EXISTS `bank`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bank` (
  `BANK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `ADDRESS_LINE_1` varchar(100) NOT NULL,
  `ADDRESS_LINE_2` varchar(100) NOT NULL,
  `CITY` varchar(100) NOT NULL,
  `STATE` varchar(2) NOT NULL,
  `ZIP_CODE` varchar(5) NOT NULL,
  `IS_INTERNATIONAL` tinyint(1) NOT NULL,
  `LAST_UPDATED_BY` varchar(45) NOT NULL,
  `LAST_UPDATED_DATE` datetime NOT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `ADDRESS_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`BANK_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `bank_contact` (
  `BANK_ID` bigint(20) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `POSITION_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BANK_ID`,`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `public`.`user`
  ADD COLUMN `USER_ADDRESS_LINE_1` VARCHAR(100) NULL AFTER `createdBy`,
  ADD COLUMN `USER_ADDRESS_LINE_2` VARCHAR(100) NULL AFTER `USER_ADDRESS_LINE_1`,
  ADD COLUMN `CITY` VARCHAR(100) NULL AFTER `USER_ADDRESS_LINE_2`,
  ADD COLUMN `STATE` VARCHAR(2) NULL AFTER `CITY`,
  ADD COLUMN `ZIP_CODE` VARCHAR(5) NULL AFTER `STATE`;

CREATE TABLE `user_address` (
  `USER_ID` bigint(20) NOT NULL,
  `USER_ADDRESS_LINE_1` varchar(100) NOT NULL,
  `USER_ADDRESS_LINE_2` varchar(100) NOT NULL,
  `CITY` varchar(100) NOT NULL,
  `STATE` varchar(2) NOT NULL,
  `ZIP_CODE` varchar(5) NOT NULL,
  `ADDRESS_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`USER_ADDRESS_LINE_1`,`USER_ADDRESS_LINE_2`,`CITY`,`STATE`,`ZIP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `account` (
  `ACCOUNT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BANK_ID` bigint(20) DEFAULT NULL,
  `ACCOUNT_TYPE` varchar(45) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `INITIAL_BALANCE` decimal(10,2) NOT NULL,
  `CURRENT_BALANCE` decimal(10,2) NOT NULL,
  `OPEN_DATE` date NOT NULL,
  `CLOSE_DATE` date NOT NULL,
  `LAST_UPDATED_BY` varchar(45) NOT NULL,
  `LAST_UPDATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_ID`),
  KEY `BANK_FK` (`BANK_ID`),
  KEY `ACCOUNT_TYPE_FK_idx` (`ACCOUNT_TYPE`),
  CONSTRAINT `BANK_FK` FOREIGN KEY (`BANK_ID`) REFERENCES `bank` (`BANK_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `account_type` (
  `ACCOUNT_TYPE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` date DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ACCOUNT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `public`.`user`
  CHANGE COLUMN `userId` `userId` BIGINT(20) NOT NULL ;

CREATE TABLE `credential` (
  `CREDENTIAL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`CREDENTIAL_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`),
  CONSTRAINT `FINANCES_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`userId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `budget` (
  `BUDGET_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `GOAL_AMOUNT` decimal(10,2) NOT NULL,
  `PERIOD` varchar(45) NOT NULL,
  PRIMARY KEY (`BUDGET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `budget_transaction` (
  `TRANSACTION_ID` bigint(20) NOT NULL,
  `BUDGET_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`TRANSACTION_ID`,`BUDGET_ID`),
  UNIQUE KEY `TRANSACTION_ID_UNIQUE` (`TRANSACTION_ID`),
  KEY `BUDGET_FK_idx` (`BUDGET_ID`),
  CONSTRAINT `BUDGET_FK` FOREIGN KEY (`BUDGET_ID`) REFERENCES `budget` (`BUDGET_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TRANSACTION_FK2` FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `transaction` (`TRANSACTION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
